version: 2
jobs:
 build:
   docker:
    - image: ubuntu:xenial
   steps:
     - checkout
     
     - run: |
         apt-get update \
         && apt-get install -y \
         build-essential debhelper \
         tcl8.6-dev autoconf \
         python3-dev python3-venv \
         dh-systemd libz-dev \
         git wget \
         devscripts 
     - run : |
        sh sensible-build.sh xenial
     - run: | 
        cd package-xenial && dpkg-buildpackage -b -uc -us