version: 2
jobs:
 build:
   docker:
    - image: debian:buster
   steps:
    - checkout
     
    - run: |
         apt-get update \
         && apt-get install -y \
         build-essential debhelper \
         tcl8.6-dev autoconf \
         python3-dev python3-venv \
         dh-systemd libz-dev

    # build the application image
     - run: cd buster && dpkg-buildpackage -b -uc -us